### ISSUE TITLE
AltDrag Disables Scroll-Wheel in Start Menu

### ISSUE THREAD

**Issue by Stewie410** [stefansundin/altdrag#109]
## My Setup
- Operating System: Windows 10 Pro
- Operating System Build: 1909
- AltDrag Version: 1.1 (release)

## Checks
- [ ] I have tested with master
- [x] I can simulate the issue easily

## Description
As soon as AltDrag is running, the scroll-up & scroll-down cease to work within the Start Menu, requiring the scroll-bar to be used instead.  Upon closing AltDrag, this behavior is immediately resolved.

**Comment by Lavuan** [comment]
mine fixed with disabling "Scroll inactive windows"

**Comment by DanEdens** [comment]
Need to add a check for this this registry option and do nothing if already set by windows.
That way it will work either way if enabled in windows, altdrag, or both.

![vivaldi_SKakyeIfM3](https://user-images.githubusercontent.com/48360111/75118398-6ecbcd80-563f-11ea-9882-d5d1fcedbf29.png)

**Comment by Stewie410** [comment]
> 
>
> mine fixed with disabling "Scroll inactive windows"

I can confirm that this does indeed restore behavior.

**Comment by savchenko** [comment]
Funny enough, can't reproduce here. Windows:
```
Version	10.0.18363 Build 18363
```

**Comment by Avispa** [comment]
I can confirm this bug ...

### *AND*

... further I can say that the same issue occurs for the "new" Windows settings dialogs tool. (Ex. dialog for *screen resolution*, etc. pp. -- just guessing the dialog/menu title but I assume it's clear what I'm refering to.)
```
Windows 10 Version 1803
```

**Comment by Avispa** [comment]
Looks like a doublet of #83 to me.

**Comment by RamonUnch** [comment]
It is a doublet of #83 indeed, @Stewie410  The easy fix is to add the start menu in the Blacklist:
Start|Windows.UI.Core.CoreWindow

This scroll bug is actually trivial to fix for all apps, it will come next week-end in my builds.
I think however that the simplest is to not use the scroll inactive windows option because this is already present under Windows 10

**Comment by Stewie410** [comment]
> 
> 
> It is a doublet of #83 indeed, @Stewie410 The easy fix is to add the start menu in the Blacklist:
> Start|Windows.UI.Core.CoreWindow
> 
> This scroll bug is actually trivial to fix for all apps, it will come next week-end in my builds.
> I think however that the simplest is to not use the scroll inactive windows option because this is already present under Windows 10

Its is _a long time_ since I've looked at this issue; but I wanted to point out that the latter workaround resolved my issue -- though, its still a workaround.

Would it be a possible option disable that option in the settings if the host OS is Windows 10; or potentially a warning label (on hover?) indicating potential issues on Windows 10?

**Comment by RamonUnch** [comment]
@Stewie410 
On my fork of AltDrag since version 1.35, the scroll inactive windows option is disabled by default (grayed) and cannot be enabled under Windows 10 unless using the .ini file directly.
Stefan no longer maintains AltDrag. To my knowledge my fork is the only updated version. checkout the change log to see the list of fixes. It fixes almost all issues people had with Window 10. So I suggest you use the updated version...

If you upgrade from version 1.1 you will loose your config because there are a lot of changes.
My fork: https://github.com/RamonUnch/AltDrag/releases
Submit issues here: https://github.com/RamonUnch/AltDrag/issues
Keep an eye for version 1.37 coming soon.

**Comment by Stewie410** [comment]
> Stefan no longer maintains AltDrag. To my knowledge my fork is the only updated version. checkout the change log to see the list of fixes.

Thanks, I wasn't aware of that -- though, looking at the commit history for this repository, I guess I could've figured that out.
